//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cicerone_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int blogs_id { get; set; }
        public int package_id { get; set; }
        public string blog_title { get; set; }
        public string blog_writer { get; set; }
        public string publish_date { get; set; }
        public string blog_details { get; set; }
        public string blog_ref { get; set; }
    
        public virtual package package { get; set; }
    }
}
