//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cicerone_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_user
    {
        public int useer_id { get; set; }
        public string username { get; set; }
        public string user_pass { get; set; }
        public string user_mail { get; set; }
        public int user_contact { get; set; }
        public string user_nid { get; set; }
    }
}
