//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cicerone_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cicerone5Entities : DbContext
    {
        public cicerone5Entities()
            : base("name=cicerone5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<blog> blogs { get; set; }
        public DbSet<booking> bookings { get; set; }
        public DbSet<db_admin> db_admin { get; set; }
        public DbSet<db_user> db_user { get; set; }
        public DbSet<package> packages { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<review_rating> review_rating { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tour> tours { get; set; }
    }
}
