//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cicerone_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        public package()
        {
            this.blogs = new HashSet<blog>();
        }
    
        public int package_id { get; set; }
        public int admin_id { get; set; }
        public string package_name { get; set; }
        public string package_source { get; set; }
        public string package_details { get; set; }
        public string package_image { get; set; }
    
        public virtual ICollection<blog> blogs { get; set; }
        public virtual db_admin db_admin { get; set; }
    }
}
