//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cicerone_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review_rating
    {
        public int rr_id { get; set; }
        public string tour_date { get; set; }
        public string reviewer_email { get; set; }
        public string review_star { get; set; }
        public string review_details { get; set; }
    }
}
