//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cicerone_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour
    {
        public int tour_id { get; set; }
        public string tour_username { get; set; }
        public string tour_usermail { get; set; }
        public string tour_date { get; set; }
        public string total_destination { get; set; }
        public string tour_details { get; set; }
    }
}
